version: "3"

networks: 
  API:
    external:
      name: API

services:

  Server:
    image: nginx:latest
    depends_on:
      - API
      - Frontend
    restart: always
    ports:
      - 8082:80
    expose:
      - "80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
    environment:
      VIRTUAL_HOST: test.com,www.test.com
    networks: 
      - default
      - API

  API:
    image: node:10
    user: node
    working_dir: /home/node/app
    volumes:
      - ./API:/home/node/app
    expose:
      - 8081
    ports:
      - 8081:8081
    command: npm run-script dev
  
  Frontend:
    image: node:10
    depends_on: 
      - API
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npm run-script build